name: Veracode Static Analysis Pipeline Scan
 
on: 
  push:
   branches: [ main ]
 
jobs:
  build-pipelinescan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - run: zip -r upload.zip ./
    
    - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - run: unzip -o pipeline-scan-LATEST.zip
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
       
    - run: java -jar pipeline-scan.jar -f upload.zip -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file upload.zip
